#!/usr/bin/env python3

import os
import sys
import pathlib
import subprocess

source_dir = pathlib.Path(__file__).parent.parent
os.environ["PYTHONPATH"] = str(source_dir / "tools")
sys.exit(subprocess.call(["mkdocs"] + sys.argv[1:] + ["-f", source_dir / "mkdocs.yml"]))
